# The global title that is displayed at the top of the pages
global_title: Clause - Style Guide

# Directory to parse
source: ./src

# Directory to build the styleguide
destination: ./styleguide

# Hologram theme
documentation_assets: ./bower_components/Cortana
custom_markdown: ./bower_components/Cortana/CortanaMarkdownRenderer.rb

# List all css to include for the styleguide render examples (path from styleguide directory)
css_include:
  - application.css
  - https://cdnjs.cloudflare.com/ajax/libs/flexboxgrid/6.3.1/flexboxgrid.min.css

# List all js to include for the styleguide render examples (path from styleguide directory)
js_include:
  - http://code.jquery.com/jquery-1.10.2.min.js

# String who is used to split the category name and create category wrapper
name_scope: ' - '
